name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      with: # Set the secret as an input
        GITHUB_TOKEN: ${{ secrets.BUNDLE_PRIVATE_KEY }}
      run: docker build --build-arg="GITHUB_TOKEN=$GITHUB_TOKEN" . --file Dockerfile --tag my-image-name:$(date +%s) 
